### ISSUE TITLE
Data Loading

### ISSUE THREAD

**Issue by steve-stnhbr** [PRBonn/HAPT#1]
Hello everybody,

I have read the presented paper and found the approach of segmenting leaves quite interesting. Sadly I was not able to get the provided code in this repository to run. I tried downloading the [SugarBeets](https://www.ipb.uni-bonn.de/data/sugarbeets2016/index.html) dataset and ingesting it using the provided functions. However my attempt did not work out because it seems that the dataset I downloaded has a quite different structure to the one expected in your code. 

Am I using the right source for the dataset or do I need to reformat the data in some way?

Any help is greatly appreciated, thank you.

Cheers,
Stefan

**Comment by matteosodano** [comment]
Hi Stefan,

unfortunately, the SugarBeets dataset that we used in the paper is not public (owned -and provided to us- by Bosch). So, that's the issue you're experiencing. I'd suggest to use the GrowliFlower dataset which is instead publicly available and we also used for the paper.
If you want to use the dataset you downloaded, you have to write the dataloader for it. Also, that dataset has for sure no leaf annotations (and I'm honestly not sure about the plant instances) so you have to remove (at least) one decoder, and keep maybe only the semantic one. 

Cheers,

Matteo & Gianmarco
